Sk/authentication
Five-Int-CSharpHub/CodeSamples pull request #9
Opened 2023-06-01 10:05 UTC by SerhiiKushanrenko

2023-07-19 17:06 UTC, PodolianNikolay commented on CodeBlocks/CodeBlocks.Authentication/BasicBearerAuth/API/Controllers/BasicBearerAuthController.cs
> +        public async Task<IActionResult> Registration(CreateUserDto userDto)
Please do not use continuous tense in the method name.
Follow the same rules that you followed for the "Login".
It is not a process, it is an action, so it should be "Register"

2023-07-19 17:44 UTC, PodolianNikolay requested changes

2023-07-19 17:44 UTC, PodolianNikolay commented on CodeBlocks/CodeBlocks.Authentication/BasicBearerAuth/API/Services/AuthenticationBearerService.cs
> +                if ((!string.IsNullOrEmpty(currentUser?.HashedPassword) &&
Is it possible to have a user without password?

2023-07-19 17:44 UTC, PodolianNikolay commented on CodeBlocks/CodeBlocks.Authentication/BasicBearerAuth/API/Services/AuthenticationBearerService.cs
> +            catch (Exception)
It will be better to include caught exception in the log.

2023-07-19 17:44 UTC, PodolianNikolay commented on CodeBlocks/CodeBlocks.Authentication/BasicBearerAuth/API/Services/AuthenticationBearerService.cs
> +        public string Registration(CreateUserDto userDto)
Register not Registration

2023-07-19 17:44 UTC, PodolianNikolay commented on CodeBlocks/CodeBlocks.Authentication/BasicBearerAuth/API/Services/AuthenticationBearerService.cs
> +                if (newUser != null)
we just added this new user, are you sure it may be null here?

2023-07-19 17:44 UTC, PodolianNikolay commented on CodeBlocks/CodeBlocks.Authentication/BasicBearerAuth/API/Services/AuthenticationBearerService.cs
> +                throw new Exception("Exception in Registration");
Why do we need to override the original exception?
That's a bad practice.
This way we are losing the original exception context and stack trace. 
And message "Exception in Registration" is not informative enough, since we can't understand what issue we got.
Please read some articles about this, for example, "Why not to rethrow exceptions" and fix this
Thank you

2023-07-19 17:44 UTC, PodolianNikolay commented on CodeBlocks/CodeBlocks.Authentication/BasicBearerAuth/API/Services/AuthenticationBearerService.cs
> +            var tokenHelper = new TokenHelper(jwtKey, jwtIssuer);
It seems like a good idea to register it as a singleton service in DI and pass jwtKey and jwtIssuer in the tokenConfig
Check it please

2023-08-01 07:56 UTC, SerhiiKushanrenko commented on CodeBlocks/CodeBlocks.Authentication/Bearer/CacheService/CacheBaseService.cs
> +            return new User();
I have changed this for - throw new Exception($"User with Email: '{userEmail}' not found");

2023-08-01 07:59 UTC, SerhiiKushanrenko commented on CodeBlocks/CodeBlocks.Authentication/BasicBearerAuth/API/Controllers/BasicBearerAuthController.cs
> +        public async Task<IActionResult> Registration(CreateUserDto userDto)
Done

2023-08-01 08:03 UTC, SerhiiKushanrenko commented on CodeBlocks/CodeBlocks.Authentication/BasicBearerAuth/API/Services/AuthenticationBearerService.cs
> +                if ((!string.IsNullOrEmpty(currentUser?.HashedPassword) &&
removed the unnecessary check

2023-08-01 08:08 UTC, SerhiiKushanrenko commented on CodeBlocks/CodeBlocks.Authentication/BasicBearerAuth/API/Services/AuthenticationBearerService.cs
> +            var tokenHelper = new TokenHelper(jwtKey, jwtIssuer);
The examples I found used this approach, but I'll look for more.

2023-08-01 08:26 UTC, SerhiiKushanrenko commented on CodeBlocks/CodeBlocks.Authentication/BasicBearerAuth/API/Services/AuthenticationBearerService.cs
> +                throw new Exception("Exception in Registration");
Done

2023-08-09 15:35 UTC, closed without merging